apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-helmchart.fullname" . }}
  labels:
    {{- include "deployment-helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 30000
      protocol: TCP
      name: http
  selector:
    {{- include "deployment-helmchart.selectorLabels" . | nindent 4 }}


